### ISSUE TITLE
Add Beautify Res as a function 

### ISSUE THREAD

**Issue by ThePrimalPea** [Tre-VN/Tre#24]
When you drag one, multiple mini Res or a whole Res folder in, this function will appear in the tool. It can sort and fix subgroups in one or all mini Res. When you merge the Res again, the tool will detect if there are too many mini Res have been fixed, it will skip and won't need to fix the whole Res again.

**Comment by harumazzz** [comment]
I'm busy -> use merge instead

**Comment by harumazzz** [comment]
Nvm let me just do it

**Comment by harumazzz** [comment]
The tool will provide a function and an option in res pack if anyone wonder. It will be asked but will not be turned on by default just for the speed. This issue is finished and will be included in 3.0.0
