### ISSUE TITLE
Add a script js that comparing rsgp file inside Packet

### ISSUE THREAD

**Issue by ThePrimalPea** [Tre-VN/Tre#25]
It should do the same with the Res one, but this time will be two Packet folders. Compares and add modified rsgp to a folder, remember to exclude 384 rsgp or any random folders inside Packet folder.

**Comment by Tre-VN** [comment]
To exclude 384, you will need to enable it in config, I will let it include 384 by default.

**Comment by harumazzz** [comment]
Perhaps this isn't necessary anymore, the two versions aren't the same in resources so this will not working fine anyways.

**Comment by ThePrimalPea** [comment]
Bro, i use it to compare two Packets in 10.2.2

**Comment by harumazzz** [comment]
I suppose? But my purpose it that the script must compare with all versions, not one version. If the script cannot do with all versions it is indeed scrapped.

**Comment by harumazzz** [comment]
Reopen the issue, the tool will provide a script can be evaluated to take res & rsgps. Although, the compare might not be perfect but this could somehow solved the current issue you occur.

**Comment by harumazzz** [comment]
I have updated the res compare to the main function. However, there is no script because js evaluate is not the default function, it is just dev function which will be terminated from the tool when release the new version to the public.
