### ISSUE TITLE
LawnStrings converting

### ISSUE THREAD

**Issue by ThePrimalPea** [Tre-VN/Tre#35]
Add function to convert LawnStrings.json to LawnStrings.txt and vice versa. LawnStrings.txt can be found from 1.4 to 6.7.1.

**Comment by harumazzz** [comment]
This should be moved to 3.0.0. However, it might appears on 3.0.1 or 3.0.2 later (the fix bugs and additional after release 3.0.0 if I have too much work todo)

**Comment by harumazzz** [comment]
Due to the recent version PopCap stopped supporting my country (Vietnam), this tool no longer maintain and this function will be scrapped.
