### ISSUE TITLE
Res to ResV2

### ISSUE THREAD

**Issue by ThePrimalPea** [Tre-VN/Tre#36]
Since 10.4.1 update, Res path has changed. Add the function to convert Res from old versions to new versions and vice versa. This would help porting stuffs to old and new versions easier.

**Comment by harumazzz** [comment]
The tool will be supporting the new path for all the functions relate to res. 
Perhaps, I need to wait for 10.4 and wait for PopCap's update to test the function if it works fine.

**Comment by harumazzz** [comment]
This is the function 22 and 23 of the tool, please use it when the public beta is open and report any bugs relate to the function if you found it and I will fix it in the release public version. I will close this issue for now.

![image](https://user-images.githubusercontent.com/114157573/222817846-4eb6a7a7-e751-4c7d-b0eb-acd37de63b9c.png)

**Comment by harumazzz** [comment]
Perhaps, this might having some bugs since it was pointed out by vitaliy, which I cannot restores it back to normal fully.
This should only be useful in porting stuffs, not reusing new resources to new resources.
