### ISSUE TITLE
 PopCap Atlas Split Advanced error

### ISSUE THREAD

**Issue by ThePrimalPea** [Tre-VN/Tre#40]
Whenever you try to split atlases from 10.2- or 10.4+, the tool will says "Execution error: Native error caught when splitting atlas".

**Comment by harumazzz** [comment]
This is indeed bug and I will adapt the changes later, it was caused by lowercase & uppercase strict requirements of the tool.

**Comment by harumazzz** [comment]
Fixed finish, now worked!
